#!/usr/bin/env bash
# Generate local-only credential files for the Sprint 6 Compose topology.
#
# Every file is a random value with no default, so the stack cannot start
# with a guessable or shared credential. Files already present are left
# untouched, so re-running this script does not rotate existing secrets.
# The secrets/ directory is excluded from version control by .gitignore.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SECRETS_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)/secrets"
mkdir -p "${SECRETS_DIR}"

random_value() {
    openssl rand -base64 32 | tr -d '\n=+/' | cut -c1-32
}

write_if_absent() {
    local name="$1"
    local path="${SECRETS_DIR}/${name}"
    if [ -f "${path}" ]; then
        echo "exists: ${name}"
        return
    fi
    random_value > "${path}"
    chmod 600 "${path}" 2>/dev/null || true
    echo "generated: ${name}"
}

write_if_absent "postgres_admin_password.txt"
write_if_absent "postgres_orchestrator_migrator_password.txt"
write_if_absent "postgres_orchestrator_app_password.txt"
write_if_absent "postgres_agent_migrator_password.txt"
write_if_absent "postgres_agent_app_password.txt"

write_if_absent "kafka_admin_password.txt"
write_if_absent "kafka_orchestrator_producer_password.txt"
write_if_absent "kafka_orchestrator_consumer_password.txt"
write_if_absent "kafka_agent_producer_password.txt"
write_if_absent "kafka_agent_consumer_password.txt"
write_if_absent "kafka_summarize_agent_producer_password.txt"
write_if_absent "kafka_summarize_agent_consumer_password.txt"
write_if_absent "kafka_review_agent_producer_password.txt"
write_if_absent "kafka_review_agent_consumer_password.txt"
write_if_absent "kafka_ui_review_agent_producer_password.txt"
write_if_absent "kafka_ui_review_agent_consumer_password.txt"
write_if_absent "kafka_architecture_review_agent_producer_password.txt"
write_if_absent "kafka_architecture_review_agent_consumer_password.txt"
write_if_absent "kafka_data_analysis_agent_producer_password.txt"
write_if_absent "kafka_data_analysis_agent_consumer_password.txt"
write_if_absent "kafka_technical_review_agent_producer_password.txt"
write_if_absent "kafka_technical_review_agent_consumer_password.txt"
write_if_absent "kafka_security_review_agent_producer_password.txt"
write_if_absent "kafka_security_review_agent_consumer_password.txt"
write_if_absent "kafka_scrum_status_agent_producer_password.txt"
write_if_absent "kafka_scrum_status_agent_consumer_password.txt"
write_if_absent "kafka_assignment_route_agent_producer_password.txt"
write_if_absent "kafka_assignment_route_agent_consumer_password.txt"

echo "Secrets are in ${SECRETS_DIR} (git-ignored)."
echo "Note: ai_router_anthropic_api_key.txt / ai_router_openai_api_key.txt are"
echo "checked-in, obviously-fake Sprint 9 placeholders (see infrastructure/README.md);"
echo "this script never generates or rotates them."
echo "Note (ADR-0027): github_token.txt is NOT generated by this script --"
echo "create it manually with a real read:project-scoped GitHub PAT once a"
echo "Projects v2 board exists, or an obviously-fake placeholder until then."
echo "Note (ADR-0028): github_token_scrum_master.txt is also NOT generated --"
echo "a separate, project+repo-scoped PAT, deliberately never the same"
echo "credential as github_token.txt (per-role least privilege)."
echo "Note (ADR-0030): github_token_product_owner.txt is also NOT generated --"
echo "a third, project+repo-scoped PAT, deliberately never the same"
echo "credential as github_token.txt or github_token_scrum_master.txt."
echo "Note (ADR-0031): github_token_principal_developer.txt is also NOT"
echo "generated -- a fourth, repo-scoped PAT. UNLIKE every other role's"
echo "credential, this one stays an obviously-fake placeholder until the"
echo "repository owner gives an explicit, separate go-ahead -- this role"
echo "can merge real pull requests against this repository's real main"
echo "branch with no per-action approval."
echo "Note (ADR-0033): github_token_frontend_specialist.txt and"
echo "github_token_postgres_specialist.txt are also NOT generated -- a"
echo "fifth and sixth repo-scoped PAT, one per review-only specialist"
echo "role (no project scope needed; neither role touches Projects v2"
echo "or can merge)."
echo "Note (ADR-0034): github_token_backend_specialist.txt is also NOT"
echo "generated -- a seventh repo-scoped PAT, review-only, deliberately"
echo "overlapping postgres-specialist's domain (see ADR-0034)."
